import Header from '@/components/shared/header';
import AppProvider from '@/providers';
import { Params } from '@/types/global';
import { Metadata } from 'next';
import { PropsWithChildren } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: PropsWithChildren<Params>) {
  return (
    <html lang="en">
      <body
      // className={`${roboto.variable} ${robotoMono.variable} ${grotesk.variable}`}
      >
        <AppProvider locale={locale}>
          <Header />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
